project:
  type: website
  output-dir: docs
  resources:
    - blog/posts/support_files/

website:
  title: "Nina Weng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pub
        text: Publications
      - href: blog
        text: Blogs
      - href: misc
        text: Responsibility
  page-footer:
    left: "(c) Nina Weng, built with quarto. Last update: Mar 2025."

format:
  html:
    theme:
      light: cosmo
    toc: false

editor: visual

